In [79]:
#Install Selenium
!pip install selenium

#Install Webdriver Manager
!pip install webdriver-manager

#Check Selenium version
import selenium
selenium.__version__

Requirement already satisfied: selenium in c:\users\maribel\anaconda3\lib\site-packages (4.28.1)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\maribel\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.3)
Requirement already satisfied: trio~=0.17 in c:\users\maribel\anaconda3\lib\site-packages (from selenium) (0.29.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\maribel\anaconda3\lib\site-packages (from selenium) (0.12.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\maribel\anaconda3\lib\site-packages (from selenium) (2024.12.14)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\maribel\anaconda3\lib\site-packages (from selenium) (4.11.0)
Requirement already satisfied: websocket-client~=1.8 in c:\users\maribel\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\maribel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (25.1.0)
Requirement already satisfied: sortedcontainers in c:\users\maribel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\maribel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.7)
Requirement already satisfied: outcome in c:\users\maribel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\maribel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\maribel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\maribel\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\maribel\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\maribel\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\maribel\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Requirement already satisfied: webdriver-manager in c:\users\maribel\anaconda3\lib\site-packages (4.0.2)
Requirement already satisfied: requests in c:\users\maribel\anaconda3\lib\site-packages (from webdriver-manager) (2.32.3)
Requirement already satisfied: python-dotenv in c:\users\maribel\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: packaging in c:\users\maribel\anaconda3\lib\site-packages (from webdriver-manager) (24.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\maribel\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\maribel\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\maribel\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\maribel\anaconda3\lib\site-packages (from requests->webdriver-manager) (2024.12.14)

'4.28.1'

In [81]:
# this library is to manipulate browser
from selenium import webdriver

# it allows you to work with differen versions of drivers
# We call ChromeDriver
# from webdriver_manager.chrome import ChromeDriverManager
import re
import time 
from selenium.webdriver.common.by import By

In [83]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

In [85]:
url     = 'https://apps5.mineco.gob.pe/transparencia/Navegador/default.aspx?y=2023&ap=Proyecto'
driver  = webdriver.Chrome()        
driver.get( url )

In [89]:
driver.maximize_window()

In [91]:
# driver.quit()

In [93]:
driver.title

'Consulta Amigable - Navegador'

In [95]:
driver.current_url

'https://apps5.mineco.gob.pe/transparencia/Navegador/Navegar_7.aspx?0=&1=M&37=M&7=&y=2023&ap=Proyecto&cpage=1&psize=2000'

In [109]:
driver.save_screenshot( '../data/img/screenshot.png' )

False

In [103]:
driver.refresh()

In [111]:
driver.quit()

In [113]:
from selenium.webdriver.chrome.options import Options

In [115]:
url     = 'https://apps5.mineco.gob.pe/transparencia/Navegador/default.aspx?y=2023&ap=Proyecto'
options = Options()
options.add_argument( '--headless' )

driver  = webdriver.Chrome( options = options )
driver.get( url )

In [117]:
driver.title

'Consulta Amigable - Navegador'

In [119]:
driver.quit()

In [121]:
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
from io import StringIO
import os
import time
import requests

In [144]:
url     = 'https://apps5.mineco.gob.pe/transparencia/Navegador/default.aspx?y=2023&ap=ActProy'
driver  = webdriver.Chrome()        
driver.get( url )
driver.maximize_window()

In [148]:
goverment_levels_button = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_BtnTipoGobierno"]' )
goverment_levels_button.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="ctl00_CPH1_BtnTipoGobierno"]"}
  (Session info: chrome=131.0.6778.266); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7236D80D5+2992373]
	(No symbol) [0x00007FF72336BFD0]
	(No symbol) [0x00007FF72320590A]
	(No symbol) [0x00007FF72325926E]
	(No symbol) [0x00007FF72325955C]
	(No symbol) [0x00007FF7232A27D7]
	(No symbol) [0x00007FF72327F3AF]
	(No symbol) [0x00007FF72329F584]
	(No symbol) [0x00007FF72327F113]
	(No symbol) [0x00007FF72324A918]
	(No symbol) [0x00007FF72324BA81]
	GetHandleVerifier [0x00007FF723736A2D+3379789]
	GetHandleVerifier [0x00007FF72374C32D+3468109]
	GetHandleVerifier [0x00007FF723740043+3418211]
	GetHandleVerifier [0x00007FF7234CC78B+847787]
	(No symbol) [0x00007FF72337757F]
	(No symbol) [0x00007FF723372FC4]
	(No symbol) [0x00007FF72337315D]
	(No symbol) [0x00007FF723362979]
	BaseThreadInitThunk [0x00007FF807F67344+20]
	RtlUserThreadStart [0x00007FF8088626B1+33]

In [150]:
frames = driver.find_elements( By.TAG_NAME, "frame" )
if frames:
    print( 'There are frames in this web page.' )
    for i, frame in enumerate( frames ):
        frame_html = frame.get_attribute( 'outerHTML' )
        print( f'HTML code of frame { i }:' )
        print( frame_html )
else:
    print('No frames found on the page.' )

There are frames in this web page.
HTML code of frame 0:
<frame name="frame0" id="frame0" src="Navegar.aspx?y=2023&amp;ap=ActProy" scrolling="yes">

In [152]:
frame = driver.find_element( By.ID, "frame0" )
driver.switch_to.frame( frame )

In [154]:
goverment_levels_button = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_BtnTipoGobierno"]' )
goverment_levels_button.click()

In [156]:
regional_governments_level_button = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_RptData_ctl03_TD0"]/input' )
regional_governments_level_button.click()

time.sleep( 2 )

sector_button = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_BtnSector"]' )
sector_button.click()

time.sleep( 2 )

regional_goverments_button = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_RptData_ctl02_TD0"]/input' )
regional_goverments_button.click()

time.sleep( 2 )

pliego_button = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_BtnPliego"]' )
pliego_button.click()

In [158]:
table_element = driver.find_element( By.XPATH, "//table[@class='Data']" )
table_html    = table_element.get_attribute( 'outerHTML' )
table_html_io = StringIO( table_html )
table_df      = pd.read_html( table_html_io )[ 0 ]

In [162]:
table_df.head( 27 )

,0,1,2,3,4,5,6,7,8,9
0,NaN,440: GOBIERNO REGIONAL DEL DEPARTAMENTO DE AMA...,1179543064,1540608616,1532841226,1506168202,1501812047,1435354196,1434920687,93.2
1,NaN,441: GOBIERNO REGIONAL DEL DEPARTAMENTO DE ANCASH,2535471411,3034507325,2700692982,2574885651,2573348946,2573085975,2571804933,84.8
2,NaN,442: GOBIERNO REGIONAL DEL DEPARTAMENTO DE APU...,1219427445,1481066763,1450345046,1439674071,1427867460,1424552445,1424088484,96.2
3,NaN,443: GOBIERNO REGIONAL DEL DEPARTAMENTO DE ARE...,2380402279,3199066208,3048096940,2988856508,2957285909,2956159533,2955145978,92.4
4,NaN,444: GOBIERNO REGIONAL DEL DEPARTAMENTO DE AYA...,1739949908,2245901927,2188831480,2177688126,2166802546,2163802520,2163609693,96.3
5,NaN,445: GOBIERNO REGIONAL DEL DEPARTAMENTO DE CAJ...,2889586900,3753119429,3634357113,3502363167,3465320550,3459808002,3459397537,92.2
6,NaN,446: GOBIERNO REGIONAL DEL DEPARTAMENTO DE CUSCO,2777544938,3427016085,3232695043,3149118852,3109043730,3092128756,3089843083,90.2
7,NaN,447: GOBIERNO REGIONAL DEL DEPARTAMENTO DE HUA...,1103900818,1418945773,1382800948,1356778343,1341690764,1340918773,1340647773,94.5
8,NaN,448: GOBIERNO REGIONAL DEL DEPARTAMENTO DE HUA...,1557605384,1996767889,1955350915,1902257438,1844381117,1836707515,1836461117,92.0
9,NaN,449: GOBIERNO REGIONAL DEL DEPARTAMENTO DE ICA,1586234614,2287996256,2252209669,2141177252,2107239132,2097727977,2097242094,91.7
10,NaN,450: GOBIERNO REGIONAL DEL DEPARTAMENTO DE JUNIN,2434904923,3185312557,3143594469,3137890191,3132855709,3127457824,3126991116,98.2
11,NaN,451: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LA ...,2809776833,3431923313,3259060228,3174289260,3093462018,3092231552,3090719458,90.1
12,NaN,452: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LAM...,1786368644,2283814253,2164424595,1990657319,1989803029,1988984699,1988007074,87.1
13,NaN,453: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LORETO,2574928800,3104134632,3060284313,2985576099,2948018160,2943625224,2937641951,94.8
14,NaN,454: GOBIERNO REGIONAL DEL DEPARTAMENTO DE MAD...,447667494,537868645,523389785,514634867,511692171,509395850,499122482,94.7
15,NaN,455: GOBIERNO REGIONAL DEL DEPARTAMENTO DE MOQ...,659808393,824833019,783517146,754792026,750958117,742685969,740238734,90.0
16,NaN,456: GOBIERNO REGIONAL DEL DEPARTAMENTO DE PASCO,802906504,1038895944,1015931829,991005871,947902029,947060482,946911015,91.2
17,NaN,457: GOBIERNO REGIONAL DEL DEPARTAMENTO DE PIURA,3203410115,3862937830,3771788104,3711109537,3679267496,3670454163,3669410261,95.0
18,NaN,458: GOBIERNO REGIONAL DEL DEPARTAMENTO DE PUNO,2516816458,3007523976,2904719966,2834207636,2801966940,2778797477,2778260138,92.4
19,NaN,459: GOBIERNO REGIONAL DEL DEPARTAMENTO DE SAN...,1903777995,2291828232,2240949242,2116461275,2075642535,2075043169,2074651444,90.5
20,NaN,460: GOBIERNO REGIONAL DEL DEPARTAMENTO DE TACNA,860030734,1004789011,931794398,914865015,895213545,893648511,893317467,88.9
21,NaN,461: GOBIERNO REGIONAL DEL DEPARTAMENTO DE TUMBES,531177430,818931178,798822226,784461258,783779232,760206526,760137528,92.8
22,NaN,462: GOBIERNO REGIONAL DEL DEPARTAMENTO DE UCA...,1276424841,1635049506,1614665711,1545415031,1531485691,1523415602,1522558509,93.2
23,NaN,463: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LIMA,1665540514,2052159243,1988278411,1935939297,1913648529,1895061410,1892880756,92.3
24,NaN,464: GOBIERNO REGIONAL DE LA PROVINCIA CONSTIT...,1350597695,1641727522,1511139393,1491311853,1490558714,1489672679,1489452121,90.7
25,NaN,465: MUNICIPALIDAD METROPOLITANA DE LIMA,76996375,114246935,104288108,94125442,93961054,89724635,89506102,78.5

In [164]:
headers_elements_r0 = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_Mt0_Row0"]' ).find_elements( By.TAG_NAME, 'td' )
headers_r0          = [ element.text for element in headers_elements_r0 ]

headers_elements_r1 = driver.find_element( By.XPATH, '//*[@id="ctl00_CPH1_Mt0_Row1"]' ).find_elements( By.TAG_NAME, 'td' )
headers_r1          = [ element.text for element in headers_elements_r1 ]

print( headers_r0, headers_r1, sep = '\n' )

[' ', 'Pliego', 'PIA', 'PIM', 'Certificación', 'Compromiso Anual', 'Ejecución', 'Avance % ']
['Atención de Compromiso Mensual ', 'Devengado ', 'Girado ']

In [166]:
driver.quit()

In [168]:
headers_r0 = [ header for header in headers_r0 if header not in [ 'Ejecución', 'Avance % ' ] ]
headers = headers_r0 + headers_r1 + [ 'Avance %' ]
print( headers )

[' ', 'Pliego', 'PIA', 'PIM', 'Certificación', 'Compromiso Anual', 'Atención de Compromiso Mensual ', 'Devengado ', 'Girado ', 'Avance %']

In [170]:
table_df.columns = headers
table_df = table_df.drop( table_df.columns[ 0 ], axis = 1 )
table_df.head( 26 )

,Pliego,PIA,PIM,Certificación,Compromiso Anual,Atención de Compromiso Mensual,Devengado,Girado,Avance %
0,440: GOBIERNO REGIONAL DEL DEPARTAMENTO DE AMA...,1179543064,1540608616,1532841226,1506168202,1501812047,1435354196,1434920687,93.2
1,441: GOBIERNO REGIONAL DEL DEPARTAMENTO DE ANCASH,2535471411,3034507325,2700692982,2574885651,2573348946,2573085975,2571804933,84.8
2,442: GOBIERNO REGIONAL DEL DEPARTAMENTO DE APU...,1219427445,1481066763,1450345046,1439674071,1427867460,1424552445,1424088484,96.2
3,443: GOBIERNO REGIONAL DEL DEPARTAMENTO DE ARE...,2380402279,3199066208,3048096940,2988856508,2957285909,2956159533,2955145978,92.4
4,444: GOBIERNO REGIONAL DEL DEPARTAMENTO DE AYA...,1739949908,2245901927,2188831480,2177688126,2166802546,2163802520,2163609693,96.3
5,445: GOBIERNO REGIONAL DEL DEPARTAMENTO DE CAJ...,2889586900,3753119429,3634357113,3502363167,3465320550,3459808002,3459397537,92.2
6,446: GOBIERNO REGIONAL DEL DEPARTAMENTO DE CUSCO,2777544938,3427016085,3232695043,3149118852,3109043730,3092128756,3089843083,90.2
7,447: GOBIERNO REGIONAL DEL DEPARTAMENTO DE HUA...,1103900818,1418945773,1382800948,1356778343,1341690764,1340918773,1340647773,94.5
8,448: GOBIERNO REGIONAL DEL DEPARTAMENTO DE HUA...,1557605384,1996767889,1955350915,1902257438,1844381117,1836707515,1836461117,92.0
9,449: GOBIERNO REGIONAL DEL DEPARTAMENTO DE ICA,1586234614,2287996256,2252209669,2141177252,2107239132,2097727977,2097242094,91.7
10,450: GOBIERNO REGIONAL DEL DEPARTAMENTO DE JUNIN,2434904923,3185312557,3143594469,3137890191,3132855709,3127457824,3126991116,98.2
11,451: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LA ...,2809776833,3431923313,3259060228,3174289260,3093462018,3092231552,3090719458,90.1
12,452: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LAM...,1786368644,2283814253,2164424595,1990657319,1989803029,1988984699,1988007074,87.1
13,453: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LORETO,2574928800,3104134632,3060284313,2985576099,2948018160,2943625224,2937641951,94.8
14,454: GOBIERNO REGIONAL DEL DEPARTAMENTO DE MAD...,447667494,537868645,523389785,514634867,511692171,509395850,499122482,94.7
15,455: GOBIERNO REGIONAL DEL DEPARTAMENTO DE MOQ...,659808393,824833019,783517146,754792026,750958117,742685969,740238734,90.0
16,456: GOBIERNO REGIONAL DEL DEPARTAMENTO DE PASCO,802906504,1038895944,1015931829,991005871,947902029,947060482,946911015,91.2
17,457: GOBIERNO REGIONAL DEL DEPARTAMENTO DE PIURA,3203410115,3862937830,3771788104,3711109537,3679267496,3670454163,3669410261,95.0
18,458: GOBIERNO REGIONAL DEL DEPARTAMENTO DE PUNO,2516816458,3007523976,2904719966,2834207636,2801966940,2778797477,2778260138,92.4
19,459: GOBIERNO REGIONAL DEL DEPARTAMENTO DE SAN...,1903777995,2291828232,2240949242,2116461275,2075642535,2075043169,2074651444,90.5
20,460: GOBIERNO REGIONAL DEL DEPARTAMENTO DE TACNA,860030734,1004789011,931794398,914865015,895213545,893648511,893317467,88.9
21,461: GOBIERNO REGIONAL DEL DEPARTAMENTO DE TUMBES,531177430,818931178,798822226,784461258,783779232,760206526,760137528,92.8
22,462: GOBIERNO REGIONAL DEL DEPARTAMENTO DE UCA...,1276424841,1635049506,1614665711,1545415031,1531485691,1523415602,1522558509,93.2
23,463: GOBIERNO REGIONAL DEL DEPARTAMENTO DE LIMA,1665540514,2052159243,1988278411,1935939297,1913648529,1895061410,1892880756,92.3
24,464: GOBIERNO REGIONAL DE LA PROVINCIA CONSTIT...,1350597695,1641727522,1511139393,1491311853,1490558714,1489672679,1489452121,90.7
25,465: MUNICIPALIDAD METROPOLITANA DE LIMA,76996375,114246935,104288108,94125442,93961054,89724635,89506102,78.5

In [172]:
path_siaf          = '../data/Part_I/SIAF'
path_siaf_regional = path_siaf + '/regional'
os.makedirs( path_siaf_regional, exist_ok = True )

In [174]:
table_path = path_siaf_regional + '/regional_table.xlsx'
table_df.to_excel( table_path, index = False )